services:
  postgres-s3-backups:
    image: nelsonmendezz/postgres-s3-backups:latest
    environment:
      CRON_SCHEDULE: "${CRON_SCHEDULE}"
      MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
      ACCESS_KEY: "${ACCESS_KEY}"
      SECRET_KEY: "${SECRET_KEY}"
      MINIO_BUCKET: "${MINIO_BUCKET}"
      DATABASE_URL: "${DATABASE_URL}"